### PR TITLE
#164047059 User should verify his email

### PR DESCRIPTION
**Pull request by Kibetchirchir**
#### Description
___
When a user signs up, he/she should be able to recieve a verification email to the email specified. The token is then sent to the endpoint to be verified

#### Type of Change
___

- [x] New Feature

#### How has this been tested
___
- [x] Unit tests
 - [x]  End to end testing

#### Checklist
___
- [x] I have added tests that prove my feature is working

#### Pivotal Tracker
___
[164047059](https://www.pivotaltracker.com/story/show/164047059)

### CODE REVIEW

**Comment by kelvinndmo** [comment]
@Kibetchirchir take note of some conflicting files

**Comment by kelvinndmo** [comment]
Resolved @Kibetchirchir ... some good work, like the way you have followed pep8 principles.

**Comment by winniekariuki** [comment]
Nice formating

**Comment by JumaKahiga** [comment]
Great work. Thanks for handling SendGrid integration.

**Review by JoanNgatia — APPROVED** [review]
LGTM

**Pull request merged**
